### ISSUE TITLE
函数或变量 'turbo' 无法识别。

### ISSUE THREAD

**Issue by YouShaoze** [mpt0816/CartesianPlanner-matlab#1]
函数或变量 'turbo' 无法识别。

出错 Plot.GetColor (line 394)
            map = turbo;

出错 Plot.PlotResult (line 315)
                    plot3(obstacle_x, obstacle_y, obstacle_t, 'Color', Plot.GetColor(obstacle_t(1), t_total));

出错 Main (line 20)
    Plot.PlotResult(env, traj)

**Comment by mpt0816** [comment]
在R2020b版本试了没有问题。
turbo是matlab的一种配色方案，您可以在matlab命令行窗口输入 turbo ，看是否有结果。如果您版本matlab没有此函数，可以使用其他配方方案。

**Comment by YouShaoze** [comment]
> 

哦哦好的，我用的是matlab2019b，可能没有这种结构用法
