### ISSUE TITLE
跑不通呀

### ISSUE THREAD

**Issue by oulongh123** [mpt0816/CartesianPlanner-matlab#2]
![image](https://github.com/mpt0816/CartesianPlanner-matlab/assets/162560656/b94e7f99-1c97-4564-b0b6-ba377633efda)

**Comment by mpt0816** [comment]
请参考https://github.com/mpt0816/CartesianPlanner-matlab/issues/1。

**Comment by mpt0816** [comment]
https://ww2.mathworks.cn/help/matlab/ref/turbo.html。
turbo在matlab2020b中推出，您的matlab版本可能低于2020b。可以选择支持的配色方案。
